### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperBoskiFaro** [firmom/centos-devtools#1]
$ docker-compose up
Starting centosdevtools_centos_1 ... done
Attaching to centosdevtools_centos_1
centos_1  | ln: failed to create symbolic link '/headless/go/src/github.com/goatcms/goatcli/goatcli': File exists
centosdevtools_centos_1 exited with code 1

**Comment by SebastianPozoga** [comment]
I fixed it a moment ago. It should work now.
